language: node_js

services:
  - couchdb

node_js:
  - "5"

sudo: false

addons:
  firefox: "53.0"
  apt:
    packages:
      - oracle-java8-set-default

script: npm run $COMMAND

before_script:
  - firefox --version
  - java -version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"

env:
  matrix:
  # break into many small tests so travis doesn't complain
  - CLIENT=selenium:firefox SUITE=1 COMMAND=test
  - CLIENT=selenium:firefox SUITE=2 COMMAND=test
  - CLIENT=selenium:firefox SUITE=3 COMMAND=test
  - CLIENT=selenium:firefox SUITE=4 COMMAND=test
  - CLIENT=selenium:firefox SUITE=5 COMMAND=test
  - CLIENT=selenium:firefox SUITE=6 COMMAND=test
  - CLIENT=selenium:firefox SUITE=7 COMMAND=test
  - CLIENT=selenium:firefox SUITE=8 COMMAND=test
  - COMMAND=test-custom

branches:
  only:
  - master
  - /^greenkeeper/.*$/
